extends:
  - ../.eslintrc.yml

env:
  browser: true

settings:
  react:
    version: '18'

plugins:
  - react-hooks

rules:
  react-hooks/exhaustive-deps:
    - error
  "@typescript-eslint/explicit-module-boundary-types": off
