printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: preserve
trailingComma: all
bracketSpacing: true
arrowParens: always
overrides:
- files: '*.html'
  options:
    printWidth: 9999
