version: "3.9"
services:
  client:
    image: client
    container_name: client
    depends_on:
      - server
    ports:
      - "8080:80"
      - "443:443"
    env_file:
      - ../.env/client.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ../nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - client_network
      - server_network
  server:
    image: server
    container_name: server
    depends_on:
      - db
    ports:
      - "5001:5001"
    env_file:
      - ../.env/api.env
    networks:
      - server_network
      - client_network
    volumes:
      - ../output:/app/output
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  transcoding-server:
    image: transcoder
    container_name: transcoding-server
    depends_on:
      - rabbitmq
    env_file:
      - ../.env/transcoder.env
    networks:
      - server_network
      - client_network
    volumes:
      - ../output:/app/output
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  db:
    image: mysql:5.7
    hostname: api-db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - server_network
    ports:
      - "3306:3306"
    env_file:
      - ../.env/db.env
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbit
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - server_network
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
volumes:
  rabbitmq:
    driver: local
  mysql-data:
    driver: local
networks:
  client_network:
    driver: bridge
  server_network:
    driver: bridge
